# Configuration for Travis CI

env:
    global:
        - secure: "EHHzggqcLY/IfN9FhPHXjaF/8P02IBhmKEEHb1kP6NsmzAp3GfI/nhJnHRrXNGlH+PwwRErkZjTFXI+DHYOz9wPvaYBsrt2p0XZka0kGGPJkOIx9ibBnyQt1BcJigrt8MvFEBNkx+u8Jv147Sp9lbJlovl7NC2DCdY4ELR4ebNN1ZNfqhbheFPLMsFNQmCDl86nG4BaWctRkaE1rJBKWARrjfRGuNzveI52/AG1f0zsgbmmIvHpzmQM73cEI6+MNGiEnUVFqm+FEIS06GjHkqdbjjmMRotxx0vusqlroE8anlOi1uecJ5O2Y7vNKzV9rx8mBI14QaWJtddgFzS2+al4mpAaRtQKhVSu3hpW/wh4PhWEq+gahhZBboe+bDttrng4q+lqZPFwnNU2PpzPCbXWyxbLXFVR3eep5ryHltga7AzoNR5c7g8z1/qoPSIeA9CnW+0grkCQLWxIkjtCnydB09brmW8q7p+uJfvPnYNjguproRbYaTN1NNd3ybcLE5qQxXdfoUTd72jBHs3YHIJASOPeg8UL+8ca7b/mIUTG3F/9nd9wMXzBXz3EFSj0inZcbstcmE1Vf33O1eOKpa2IbFr/NMBMn3DX6JWnr2BjG2p4QTpqiqtryvmpwbTFqYUG8rWxqf4GP/5RhLi5niATTTo2l71S+cZZmxysEB9s="

languages: c

branches:
    only:
        - master
        - covscan

sudo: false

os:
    - linux
    - osx

compilers:
    - gcc
    - clang

matrix:
    fast_finish: true
    exclude:
        - compiler: gcc
          os: osx

install:
    - ./.travis-install.sh

script:
    - if [ -z ${COVERITY_SCAN_BRANCH} ] || [ ${COVERITY_SCAN_BRANCH} != 1 ] ; then CPPFLAGS="-isystem $HOME/deproot/include" ./configure --with-libgit2=$HOME/deproot && make && make test ; fi

after_success:
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then COVERALLS=1 make clean coverage ; fi

addons:
    apt:
        packages:
            - libpq-dev
            - libmysqlclient-dev
            - libsqlite3-dev
            - libcunit1
            - libcunit1-dev
    coverity_scan:
        project:
            name: "thentenaar/mmm"
            description: "Minimal Migration Manager"
        notification_email: tim@hentenaar.com
        build_command_prepend: ./configure --with-libgit2=$HOME/deproot
        build_command: make
        branch_pattern: covscan
