# Configuration for Travis CI

languages: c

branches:
    only:
        - master
        - covscan

os:
    - linux

compilers:
    - gcc

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libpq-dev libmysqlclient-dev libsqlite3-dev
    - sudo apt-get install -qq libcunit1 libcunit1-dev
    - sudo pip install cpp-coveralls gcovr
    - wget https://github.com/libgit2/libgit2/archive/v0.23.0-rc1.tar.gz
    - tar -xzf v0.23.0-rc1.tar.gz
    - mkdir -p libgit2-build && cd libgit2-build
    - cmake --build=. ../libgit2-0.23.0-rc1 && make && sudo make install
    - cd .. ; rm -rf libgit2-build libgit2-0.23.0-rc1

script:
    - if [ -z ${COVERITY_SCAN_BRANCH} ] || [ ${COVERITY_SCAN_BRANCH} != 1 ] ; then make; fi
    - CUNIT_LIBS=-lcunit make check

after_success:
    - CUNIT_LIBS=-lcunit COVERALLS=1 make clean coverage

