name: Release
on:
  push:
    tags:
      - v*
permissions:
  contents: write
jobs:
  release:
    if: github.repository == 'thentenaar/mmm'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.changelog }}

